### ISSUE TITLE
App threw an error during load ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by freedomtrain** [mattdesl/color-wander#15]
When I run npm start I receive the following error message 

App threw an error during load
ReferenceError: navigator is not defined
    at /Users/hampton/Desktop/dev/app/color-wander/node_modules/fastclick/lib/fastclick.js:181:29
    at Object.<anonymous> (/Users/hampton/Desktop/dev/app/color-wander/node_modules/fastclick/lib/fastclick.js:841:2)

**Comment by benjaminrbarnes** [comment]
When are you recieving this error? Do you have all the dependcies installed? See issue https://github.com/mattdesl/color-wander/issues/8
