### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ManuChalela** [mattdesl/color-wander#18]
Hello, when i try install color-wander occurs this following error:

> Your environment has been set up for using Node.js 8.2.1 (x64) and npm.
> 
> E:\Documents\GitHub>git clone https://github.com/mattdesl/color-wander.git
> Cloning into 'color-wander'...
> remote: Counting objects: 122, done.
> remote: Total 122 (delta 0), reused 0 (delta 0), pack-reused 122R
> Receiving objects: 100% (122/122), 1.93 MiB | 546.00 KiB/s, done.
> Resolving deltas: 100% (57/57), done.
> 
> E:\Documents\GitHub>cd color-wander
> 
> E:\Documents\GitHub\color-wander>npm install
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> 
> > canvas@1.6.6 install E:\Documents\GitHub\color-wander\node_modules\canvas
> > node-gyp rebuild
> 
> 
> E:\Documents\GitHub\color-wander\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\My User\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Warning: Missing input files:
> C:\GTK\bin\zlib1.dll
> C:\GTK\bin\libexpat-1.dll
> C:\GTK\bin\libpng14-14.dll
> C:\GTK\bin\libcairo-2.dll
> C:\GTK\bin\libfontconfig-1.dll
> C:\GTK\bin\libfreetype-6.dll
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   Canvas.cc
>   CanvasGradient.cc
>   CanvasPattern.cc
>   CanvasRenderingContext2d.cc
>   color.cc
>   Image.cc
>   ImageData.cc
>   init.cc
>   win_delay_load_hook.cc
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\init.cc) [E:\Documents\GitHub\color-wander\node_modules
> \canvas\build\canvas.vcxproj]
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [E:\Documents\GitHub\color
> -wander\node_modules\canvas\build\canvas.vcxproj]
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\Image.cc) [E:\Documents\GitHub\color-wander\node_module
> s\canvas\build\canvas.vcxproj]
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\Canvas.cc) [E:\Documents\GitHub\color-wander\node_modul
> es\canvas\build\canvas.vcxproj]
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [E:\Documents\GitHub\color-wander\nod
> e_modules\canvas\build\canvas.vcxproj]
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\ImageData.cc) [E:\Documents\GitHub\color-wander\node_mo
> dules\canvas\build\canvas.vcxproj]
> e:\documents\github\color-wander\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'ca
> iro.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [E:\Documents\GitHub\color-wander\no
> de_modules\canvas\build\canvas.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\My User\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:125:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 10.0.15063
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My User\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd E:\Documents\GitHub\color-wander\node_modules\canvas
> gyp ERR! node -v v8.2.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas@1.6.6 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the canvas@1.6.6 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\My User\AppData\Roaming\npm-cache\_logs\2017-08-08T01_42_52_812Z-debug.log
> 
> E:\Documents\GitHub\color-wander

Windows 10 
Visual Studio 2015 
node v8.2.1 
npm v.5.3.0

How to solve this? Thanks you all.

**Comment by benjaminrbarnes** [comment]
See this issue: https://github.com/mattdesl/color-wander/issues/8
